<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.runner.utility" Version="2.6.2" />
    <Compile Include="../Shared/*.cs" Link="Shared/%(Filename)%(Extension)" />
    <None Update="*.cmd;*.sh" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
