//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ros2cs.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

#nullable enable

namespace Rosidl.Messages.Sensor
{
    /// <summary>
    /// Message interface definition for <c>sensor_msgs/msg/BatteryState</c>.
    /// </summary>
    [global::Rosidl.Runtime.TypeSupportAttribute("sensor_msgs/msg/BatteryState")]
    public unsafe partial class BatteryState : global::Rosidl.Runtime.IMessage
    {
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public static string TypeSupportName => "sensor_msgs/msg/BatteryState";
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public static global::Rosidl.Runtime.TypeSupportHandle GetTypeSupportHandle()
        {
            return new global::Rosidl.Runtime.TypeSupportHandle(_PInvoke(), global::Rosidl.Runtime.HandleType.Message);
            
            [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
            [global::System.Runtime.InteropServices.DllImportAttribute("sensor_msgs__rosidl_typesupport_c", EntryPoint = "rosidl_typesupport_c__get_message_type_support_handle__sensor_msgs__msg__BatteryState")]
            static extern nint _PInvoke();
        }
        
        /// <summary>
        /// Create a new instance of <see cref="BatteryState"/> with fields initialized to specified values.
        /// </summary>
        /// <param name='header'>
        /// Originally defined as: <c><![CDATA[std_msgs/Header header]]></c>
        /// </param>
        /// <param name='voltage'>
        /// Voltage in Volts (Mandatory)
        /// <para>(originally defined as: <c><![CDATA[float32 voltage]]></c>)</para>
        /// </param>
        /// <param name='temperature'>
        /// Temperature in Degrees Celsius (If unmeasured NaN)
        /// <para>(originally defined as: <c><![CDATA[float32 temperature]]></c>)</para>
        /// </param>
        /// <param name='current'>
        /// Negative when discharging (A)  (If unmeasured NaN)
        /// <para>(originally defined as: <c><![CDATA[float32 current]]></c>)</para>
        /// </param>
        /// <param name='charge'>
        /// Current charge in Ah  (If unmeasured NaN)
        /// <para>(originally defined as: <c><![CDATA[float32 charge]]></c>)</para>
        /// </param>
        /// <param name='capacity'>
        /// Capacity in Ah (last full capacity)  (If unmeasured NaN)
        /// <para>(originally defined as: <c><![CDATA[float32 capacity]]></c>)</para>
        /// </param>
        /// <param name='designCapacity'>
        /// Capacity in Ah (design capacity)  (If unmeasured NaN)
        /// <para>(originally defined as: <c><![CDATA[float32 design_capacity]]></c>)</para>
        /// </param>
        /// <param name='percentage'>
        /// Charge percentage on 0 to 1 range  (If unmeasured NaN)
        /// <para>(originally defined as: <c><![CDATA[float32 percentage]]></c>)</para>
        /// </param>
        /// <param name='powerSupplyStatus'>
        /// The charging status as reported. Values defined above
        /// <para>(originally defined as: <c><![CDATA[uint8 power_supply_status]]></c>)</para>
        /// </param>
        /// <param name='powerSupplyHealth'>
        /// The battery health metric. Values defined above
        /// <para>(originally defined as: <c><![CDATA[uint8 power_supply_health]]></c>)</para>
        /// </param>
        /// <param name='powerSupplyTechnology'>
        /// The battery chemistry. Values defined above
        /// <para>(originally defined as: <c><![CDATA[uint8 power_supply_technology]]></c>)</para>
        /// </param>
        /// <param name='present'>
        /// True if the battery is present
        /// <para>(originally defined as: <c><![CDATA[bool present]]></c>)</para>
        /// </param>
        /// <param name='cellVoltage'>
        /// An array of individual cell voltages for each cell in the pack
        /// <para>(originally defined as: <c><![CDATA[float32[] cell_voltage]]></c>)</para>
        /// </param>
        /// <param name='cellTemperature'>
        /// An array of individual cell temperatures for each cell in the pack
        /// <para>(originally defined as: <c><![CDATA[float32[] cell_temperature]]></c>)</para>
        /// </param>
        /// <param name='location'>
        /// The location into which the battery is inserted. (slot number or plug)
        /// <para>(originally defined as: <c><![CDATA[string location]]></c>)</para>
        /// </param>
        /// <param name='serialNumber'>
        /// The best approximation of the battery serial number
        /// <para>(originally defined as: <c><![CDATA[string serial_number]]></c>)</para>
        /// </param>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public BatteryState(
            global::Rosidl.Messages.Std.Header? @header = null,
            float @voltage = 0f,
            float @temperature = 0f,
            float @current = 0f,
            float @charge = 0f,
            float @capacity = 0f,
            float @designCapacity = 0f,
            float @percentage = 0f,
            byte @powerSupplyStatus = 0,
            byte @powerSupplyHealth = 0,
            byte @powerSupplyTechnology = 0,
            bool @present = false,
            float[]? @cellVoltage = null,
            float[]? @cellTemperature = null,
            string @location = "",
            string @serialNumber = ""
        )
        {
            Header = @header ?? new global::Rosidl.Messages.Std.Header();
            Voltage = @voltage;
            Temperature = @temperature;
            Current = @current;
            Charge = @charge;
            Capacity = @capacity;
            DesignCapacity = @designCapacity;
            Percentage = @percentage;
            PowerSupplyStatus = @powerSupplyStatus;
            PowerSupplyHealth = @powerSupplyHealth;
            PowerSupplyTechnology = @powerSupplyTechnology;
            Present = @present;
            CellVoltage = @cellVoltage ?? global::System.Array.Empty<float>();
            CellTemperature = @cellTemperature ?? global::System.Array.Empty<float>();
            Location = @location;
            SerialNumber = @serialNumber;
        }
        
        
        /// <summary>
        /// Create a new instance of <see cref="BatteryState"/>, and copy its data from the specified <see cref="Priv"/> structure.
        /// </summary>
        /// <param name="priv">The <see cref="Priv"/> structure to be copied from.</param>
        /// <param name="textEncoding">Text encoding of the strings in the <see cref="Priv"/> structure and its containing structures, if any.</param>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public BatteryState(in Priv priv, global::System.Text.Encoding textEncoding)
        {
            this.Header = new global::Rosidl.Messages.Std.Header(in priv.Header, textEncoding);
            this.Voltage = priv.Voltage;
            this.Temperature = priv.Temperature;
            this.Current = priv.Current;
            this.Charge = priv.Charge;
            this.Capacity = priv.Capacity;
            this.DesignCapacity = priv.DesignCapacity;
            this.Percentage = priv.Percentage;
            this.PowerSupplyStatus = priv.PowerSupplyStatus;
            this.PowerSupplyHealth = priv.PowerSupplyHealth;
            this.PowerSupplyTechnology = priv.PowerSupplyTechnology;
            this.Present = priv.Present;
            this.CellVoltage = priv.CellVoltage.AsSpan().ToArray();
            this.CellTemperature = priv.CellTemperature.AsSpan().ToArray();
            this.Location = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.Location.AsSpan(), textEncoding);
            this.SerialNumber = global::Rosidl.Runtime.Interop.StringMarshal.CreatePooledString(priv.SerialNumber.AsSpan(), textEncoding);
        }
        
        
        /// <summary>
        /// Power supply status constants
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_STATUS_UNKNOWN = 0]]></c>
        /// </remarks>
        public const byte POWER_SUPPLY_STATUS_UNKNOWN = 0;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_STATUS_CHARGING = 1]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_STATUS_CHARGING = 1;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_STATUS_DISCHARGING = 2]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_STATUS_DISCHARGING = 2;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_STATUS_NOT_CHARGING = 3]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_STATUS_NOT_CHARGING = 3;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_STATUS_FULL = 4]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_STATUS_FULL = 4;
        
        /// <summary>
        /// Power supply health constants
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_HEALTH_UNKNOWN = 0]]></c>
        /// </remarks>
        public const byte POWER_SUPPLY_HEALTH_UNKNOWN = 0;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_HEALTH_GOOD = 1]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_HEALTH_GOOD = 1;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_HEALTH_OVERHEAT = 2]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_HEALTH_OVERHEAT = 2;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_HEALTH_DEAD = 3]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_HEALTH_DEAD = 3;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_HEALTH_OVERVOLTAGE = 4]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_HEALTH_OVERVOLTAGE = 4;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_HEALTH_UNSPEC_FAILURE = 5]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_HEALTH_UNSPEC_FAILURE = 5;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_HEALTH_COLD = 6]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_HEALTH_COLD = 6;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE = 7]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE = 7;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE = 8]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE = 8;
        
        /// <summary>
        /// Power supply technology (chemistry) constants
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_TECHNOLOGY_UNKNOWN = 0]]></c>
        /// </remarks>
        public const byte POWER_SUPPLY_TECHNOLOGY_UNKNOWN = 0;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_TECHNOLOGY_NIMH = 1]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_TECHNOLOGY_NIMH = 1;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_TECHNOLOGY_LION = 2]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_TECHNOLOGY_LION = 2;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_TECHNOLOGY_LIPO = 3]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_TECHNOLOGY_LIPO = 3;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_TECHNOLOGY_LIFE = 4]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_TECHNOLOGY_LIFE = 4;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_TECHNOLOGY_NICD = 5]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_TECHNOLOGY_NICD = 5;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[uint8 POWER_SUPPLY_TECHNOLOGY_LIMN = 6]]></c>
        /// </summary>
        public const byte POWER_SUPPLY_TECHNOLOGY_LIMN = 6;
        
        /// <summary>
        /// Originally defined as: <c><![CDATA[std_msgs/Header header]]></c>
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public global::Rosidl.Messages.Std.Header Header { get; set; }
        
        /// <summary>
        /// Voltage in Volts (Mandatory)
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[float32 voltage]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public float Voltage { get; set; }
        
        /// <summary>
        /// Temperature in Degrees Celsius (If unmeasured NaN)
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[float32 temperature]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public float Temperature { get; set; }
        
        /// <summary>
        /// Negative when discharging (A)  (If unmeasured NaN)
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[float32 current]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public float Current { get; set; }
        
        /// <summary>
        /// Current charge in Ah  (If unmeasured NaN)
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[float32 charge]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public float Charge { get; set; }
        
        /// <summary>
        /// Capacity in Ah (last full capacity)  (If unmeasured NaN)
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[float32 capacity]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public float Capacity { get; set; }
        
        /// <summary>
        /// Capacity in Ah (design capacity)  (If unmeasured NaN)
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[float32 design_capacity]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public float DesignCapacity { get; set; }
        
        /// <summary>
        /// Charge percentage on 0 to 1 range  (If unmeasured NaN)
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[float32 percentage]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public float Percentage { get; set; }
        
        /// <summary>
        /// The charging status as reported. Values defined above
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[uint8 power_supply_status]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public byte PowerSupplyStatus { get; set; }
        
        /// <summary>
        /// The battery health metric. Values defined above
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[uint8 power_supply_health]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public byte PowerSupplyHealth { get; set; }
        
        /// <summary>
        /// The battery chemistry. Values defined above
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[uint8 power_supply_technology]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public byte PowerSupplyTechnology { get; set; }
        
        /// <summary>
        /// True if the battery is present
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[bool present]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public bool Present { get; set; }
        
        /// <summary>
        /// An array of individual cell voltages for each cell in the pack
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[float32[] cell_voltage]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public float[] CellVoltage { get; set; }
        
        /// <summary>
        /// An array of individual cell temperatures for each cell in the pack
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[float32[] cell_temperature]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public float[] CellTemperature { get; set; }
        
        /// <summary>
        /// The location into which the battery is inserted. (slot number or plug)
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[string location]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public string Location { get; set; }
        
        /// <summary>
        /// The best approximation of the battery serial number
        /// </summary>
        /// <remarks>
        /// Originally defined as: <c><![CDATA[string serial_number]]></c>
        /// </remarks>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public string SerialNumber { get; set; }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public void WriteTo(nint data, global::System.Text.Encoding textEncoding)
        {
            WriteTo(ref global::System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()), textEncoding);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public void WriteTo(ref Priv priv, global::System.Text.Encoding textEncoding)
        {
            this.Header.WriteTo(ref priv.Header, textEncoding);
            priv.Voltage = this.Voltage;
            priv.Temperature = this.Temperature;
            priv.Current = this.Current;
            priv.Charge = this.Charge;
            priv.Capacity = this.Capacity;
            priv.DesignCapacity = this.DesignCapacity;
            priv.Percentage = this.Percentage;
            priv.PowerSupplyStatus = this.PowerSupplyStatus;
            priv.PowerSupplyHealth = this.PowerSupplyHealth;
            priv.PowerSupplyTechnology = this.PowerSupplyTechnology;
            priv.Present = this.Present;
            priv.CellVoltage.CopyFrom(this.CellVoltage);
            priv.CellTemperature.CopyFrom(this.CellTemperature);
            priv.Location.CopyFrom(this.Location, textEncoding);
            priv.SerialNumber.CopyFrom(this.SerialNumber, textEncoding);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public static global::Rosidl.Runtime.IMessage CreateFrom(nint data, global::System.Text.Encoding textEncoding)
        {
            return new BatteryState(in global::System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()), textEncoding);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public static nint UnsafeCreate()
        {
            return new(Priv.Create());
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public static void UnsafeDestroy(nint data)
        {
            Priv.Destroy((Priv*)data);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public static bool UnsafeInitialize(nint data)
        {
            return Priv.TryInitialize(out System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public static void UnsafeFinalize(nint data)
        {
            Priv.Finalize(ref System.Runtime.CompilerServices.Unsafe.AsRef<Priv>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public static bool UnsafeInitializeSequence(int size, nint data)
        {
            return PrivSequence.TryInitialize(size, out System.Runtime.CompilerServices.Unsafe.AsRef<PrivSequence>(data.ToPointer()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
        public static void UnsafeFinalizeSequence(nint data)
        {
            PrivSequence.Finalize(ref System.Runtime.CompilerServices.Unsafe.AsRef<PrivSequence>(data.ToPointer()));
        }
        
        /// <summary>
        /// Blittable native structure for <c>sensor_msgs/msg/BatteryState</c>.
        /// </summary>
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
        public partial struct Priv : global::System.IEquatable<Priv>, global::System.IDisposable
        {
            /// <summary>
            /// Originally defined as: <c><![CDATA[std_msgs/Header header]]></c>
            /// </summary>
            public global::Rosidl.Messages.Std.Header.Priv Header;
            
            /// <summary>
            /// Voltage in Volts (Mandatory)
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[float32 voltage]]></c>
            /// </remarks>
            public float Voltage;
            
            /// <summary>
            /// Temperature in Degrees Celsius (If unmeasured NaN)
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[float32 temperature]]></c>
            /// </remarks>
            public float Temperature;
            
            /// <summary>
            /// Negative when discharging (A)  (If unmeasured NaN)
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[float32 current]]></c>
            /// </remarks>
            public float Current;
            
            /// <summary>
            /// Current charge in Ah  (If unmeasured NaN)
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[float32 charge]]></c>
            /// </remarks>
            public float Charge;
            
            /// <summary>
            /// Capacity in Ah (last full capacity)  (If unmeasured NaN)
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[float32 capacity]]></c>
            /// </remarks>
            public float Capacity;
            
            /// <summary>
            /// Capacity in Ah (design capacity)  (If unmeasured NaN)
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[float32 design_capacity]]></c>
            /// </remarks>
            public float DesignCapacity;
            
            /// <summary>
            /// Charge percentage on 0 to 1 range  (If unmeasured NaN)
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[float32 percentage]]></c>
            /// </remarks>
            public float Percentage;
            
            /// <summary>
            /// The charging status as reported. Values defined above
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[uint8 power_supply_status]]></c>
            /// </remarks>
            public byte PowerSupplyStatus;
            
            /// <summary>
            /// The battery health metric. Values defined above
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[uint8 power_supply_health]]></c>
            /// </remarks>
            public byte PowerSupplyHealth;
            
            /// <summary>
            /// The battery chemistry. Values defined above
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[uint8 power_supply_technology]]></c>
            /// </remarks>
            public byte PowerSupplyTechnology;
            
            /// <summary>
            /// True if the battery is present
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[bool present]]></c>
            /// </remarks>
            public bool Present;
            
            /// <summary>
            /// An array of individual cell voltages for each cell in the pack
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[float32[] cell_voltage]]></c>
            /// </remarks>
            public global::Rosidl.Runtime.Interop.FloatSequence CellVoltage;
            
            /// <summary>
            /// An array of individual cell temperatures for each cell in the pack
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[float32[] cell_temperature]]></c>
            /// </remarks>
            public global::Rosidl.Runtime.Interop.FloatSequence CellTemperature;
            
            /// <summary>
            /// The location into which the battery is inserted. (slot number or plug)
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[string location]]></c>
            /// </remarks>
            public global::Rosidl.Runtime.Interop.CString Location;
            
            /// <summary>
            /// The best approximation of the battery serial number
            /// </summary>
            /// <remarks>
            /// Originally defined as: <c><![CDATA[string serial_number]]></c>
            /// </remarks>
            public global::Rosidl.Runtime.Interop.CString SerialNumber;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public Priv()
            {
                ThrowIfNonSuccess(TryInitialize(out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public Priv(Priv src)
                : this(in src)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public Priv(in Priv src)
                : this()
            {
                CopyFrom(in src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public Priv(Priv* src)
                : this()
            {
                CopyFrom(src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public void Dispose()
            {
                Finalize(ref this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public void CopyFrom(Priv src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public void CopyFrom(in Priv src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public void CopyFrom(Priv* src)
            {
                fixed (Priv* pThis = &this)
                {
                    ThrowIfNonSuccess(TryCopy(src, pThis));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            private static bool TryCopy(in Priv input, out Priv output)
            {
                fixed (Priv* pInput = &input, pOutput = &output)
                {
                    return TryCopy(pInput, pOutput);
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public bool Equals(Priv other)
            {
                return Priv.AreEqual(in other, in this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public override bool Equals(object? obj) => obj is Priv s ? this.Equals(s) : false;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public override int GetHashCode()
            {
                var __hashCode = new global::System.HashCode();
                __hashCode.Add(this.Header);
                __hashCode.Add(this.Voltage);
                __hashCode.Add(this.Temperature);
                __hashCode.Add(this.Current);
                __hashCode.Add(this.Charge);
                __hashCode.Add(this.Capacity);
                __hashCode.Add(this.DesignCapacity);
                __hashCode.Add(this.Percentage);
                __hashCode.Add(this.PowerSupplyStatus);
                __hashCode.Add(this.PowerSupplyHealth);
                __hashCode.Add(this.PowerSupplyTechnology);
                __hashCode.Add(this.Present);
                __hashCode.Add(this.CellVoltage);
                __hashCode.Add(this.CellTemperature);
                __hashCode.Add(this.Location);
                __hashCode.Add(this.SerialNumber);
                return __hashCode.ToHashCode();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public static bool operator ==(Priv lhs, Priv rhs)
            {
                return lhs.Equals(rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public static bool operator !=(Priv lhs, Priv rhs)
            {
                return !(lhs == rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public static Priv* Create()
            {
                return _PInvoke();
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("sensor_msgs__rosidl_generator_c", EntryPoint = "sensor_msgs__msg__BatteryState__create")]
                static extern Priv* _PInvoke();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public static void Destroy(Priv* msg)
            {
                _PInvoke(msg);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("sensor_msgs__rosidl_generator_c", EntryPoint = "sensor_msgs__msg__BatteryState__destroy")]
                static extern void _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public static bool TryInitialize(out Priv msg)
            {
                fixed (Priv* pMsg = &msg)
                {
                    return _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("sensor_msgs__rosidl_generator_c", EntryPoint = "sensor_msgs__msg__BatteryState__init")]
                static extern bool _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public static void Finalize(ref Priv msg)
            {
                fixed (Priv* pMsg = &msg)
                {
                    _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("sensor_msgs__rosidl_generator_c", EntryPoint = "sensor_msgs__msg__BatteryState__fini")]
                static extern void _PInvoke(Priv* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            private static bool AreEqual(in Priv lhs, in Priv rhs)
            {
                fixed (Priv* plhs = &lhs, prhs = &rhs)
                {
                    return _PInvoke(plhs, prhs);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("sensor_msgs__rosidl_generator_c", EntryPoint = "sensor_msgs__msg__BatteryState__are_qual")]
                static extern bool _PInvoke(Priv* lhs, Priv* rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            private static bool TryCopy(Priv* input, Priv* output)
            {
                return _PInvoke(input, output);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("sensor_msgs__rosidl_generator_c", EntryPoint = "sensor_msgs__msg__BatteryState__copy")]
                static extern bool _PInvoke(Priv* input, Priv* output);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public static void ThrowIfNonSuccess(bool ret, [global::System.Runtime.CompilerServices.CallerMemberNameAttribute]
            string caller = "")
            {
                if (!ret)
                {
                    throw new global::Rosidl.Runtime.RosidlException($"An error occurred when calling 'global::Rosidl.Messages.Sensor.BatteryState.Priv.{caller}'.");
                }
            }
        }
        
        /// <summary>
        /// Blittable native sequence structure for <c>sensor_msgs/msg/BatteryState</c>.
        /// </summary>
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
        public partial struct PrivSequence : global::System.IEquatable<PrivSequence>, global::System.IDisposable
        {
            private Priv* __data;
            
            private nuint __size;
            
            private nuint __capacity;
            
            public int Size => (int)__size;
            
            public int Capcacity => (int)__capacity;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public PrivSequence()
                : this(0)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public PrivSequence(int size)
            {
                ThrowIfNonSuccess(TryInitialize(size, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public PrivSequence(PrivSequence src)
                : this(in src)
            {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public PrivSequence(in PrivSequence src)
                : this()
            {
                CopyFrom(in src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public PrivSequence(PrivSequence* src)
                : this()
            {
                CopyFrom(src); 
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public PrivSequence(System.ReadOnlySpan<Priv> src)
                : this(src.Length)
            {
                src.CopyTo(AsSpan());
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public void Dispose()
            {
                Finalize(ref this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public System.Span<Priv> AsSpan()
            {
                return new(__data, Size);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public void CopyFrom(System.ReadOnlySpan<Priv> src)
            {
                Finalize(ref this);
                ThrowIfNonSuccess(TryInitialize(src.Length, out this));
                src.CopyTo(AsSpan());
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public void CopyFrom(PrivSequence src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public void CopyFrom(in PrivSequence src)
            {
                ThrowIfNonSuccess(TryCopy(in src, out this));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public void CopyFrom(PrivSequence* src)
            {
                fixed (PrivSequence* pThis = &this)
                {
                    ThrowIfNonSuccess(TryCopy(src, pThis));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            private static bool TryCopy(in PrivSequence input, out PrivSequence output)
            {
                fixed (PrivSequence* pInput = &input, pOutput = &output)
                {
                    return TryCopy(pInput, pOutput);
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public bool Equals(PrivSequence other)
            {
                return PrivSequence.AreEqual(in other, in this);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public override bool Equals(object? obj) => obj is PrivSequence s ? this.Equals(s) : false;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public override int GetHashCode()
            {
                return global::System.HashCode.Combine((nint)__data, __size, __capacity);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public static bool operator ==(PrivSequence lhs, PrivSequence rhs)
            {
                return lhs.Equals(rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public static bool operator !=(PrivSequence lhs, PrivSequence rhs)
            {
                return !(lhs == rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public static PrivSequence* Create()
            {
                return _PInvoke();
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("sensor_msgs__rosidl_generator_c", EntryPoint = "sensor_msgs__msg__BatteryState__Sequence__create")]
                static extern PrivSequence* _PInvoke();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public static void Destroy(PrivSequence* msg)
            {
                _PInvoke(msg);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("sensor_msgs__rosidl_generator_c", EntryPoint = "sensor_msgs__msg__BatteryState__Sequence__destroy")]
                static extern void _PInvoke(PrivSequence* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public static bool TryInitialize(int size, out PrivSequence msg)
            {
                fixed (PrivSequence* pMsg = &msg)
                {
                    return _PInvoke(pMsg, (uint)size);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("sensor_msgs__rosidl_generator_c", EntryPoint = "sensor_msgs__msg__BatteryState__Sequence__init")]
                static extern bool _PInvoke(PrivSequence* msg, nuint size);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public static void Finalize(ref PrivSequence msg)
            {
                fixed (PrivSequence* pMsg = &msg)
                {
                    _PInvoke(pMsg);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("sensor_msgs__rosidl_generator_c", EntryPoint = "sensor_msgs__msg__BatteryState__Sequence__fini")]
                static extern void _PInvoke(PrivSequence* msg);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            private static bool AreEqual(in PrivSequence lhs, in PrivSequence rhs)
            {
                fixed (PrivSequence* plhs = &lhs, prhs = &rhs)
                {
                    return _PInvoke(plhs, prhs);
                }
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("sensor_msgs__rosidl_generator_c", EntryPoint = "sensor_msgs__msg__BatteryState__Sequence__are_qual")]
                static extern bool _PInvoke(PrivSequence* lhs, PrivSequence* rhs);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            private static bool TryCopy(PrivSequence* input, PrivSequence* output)
            {
                return _PInvoke(input, output);
                
                [global::System.Runtime.InteropServices.SuppressGCTransitionAttribute]
                [global::System.Runtime.InteropServices.DllImportAttribute("sensor_msgs__rosidl_generator_c", EntryPoint = "sensor_msgs__msg__BatteryState__Sequence__copy")]
                static extern bool _PInvoke(PrivSequence* input, PrivSequence* output);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Rosidl.Runtime.Generator.CSharp", "1.0.0")]
            public static void ThrowIfNonSuccess(bool ret, [global::System.Runtime.CompilerServices.CallerMemberNameAttribute]
            string caller = "")
            {
                if (!ret)
                {
                    throw new global::Rosidl.Runtime.RosidlException($"An error occurred when calling 'global::Rosidl.Messages.Sensor.BatteryState.PrivSequence.{caller}'.");
                }
            }
        }
    }
}
