namespace Rcl.Interop;

internal enum rmw_ret
{
    RMW_RET_OK = 0,
    RMW_RET_ERROR = 1,
    RMW_RET_TIMEOUT = 2,
    RMW_RET_UNSUPPORTED = 3,
    RMW_RET_BAD_ALLOC = 10,
    RMW_RET_INVALID_ARGUMENT = 11,
    RMW_RET_INCORRECT_RMW_IMPLEMENTATION = 12,
    RMW_RET_NODE_NAME_NON_EXISTENT = 13
}

internal enum rcl_ret
{
    RCL_RET_OK = rmw_ret.RMW_RET_OK,
    RCL_RET_ERROR = rmw_ret.RMW_RET_ERROR,
    RCL_RET_TIMEOUT = rmw_ret.RMW_RET_TIMEOUT,
    RCL_RET_UNSUPPORTED = rmw_ret.RMW_RET_UNSUPPORTED,
    RCL_RET_BAD_ALLOC = rmw_ret.RMW_RET_BAD_ALLOC,
    RCL_RET_INVALID_ARGUMENT = rmw_ret.RMW_RET_INVALID_ARGUMENT,
    RCL_RET_NODE_NAME_NON_EXISTENT = 203
}