<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Rcl.NET.TestAdapter</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="17.8.0" />
    <Compile Include="../Shared/*.cs" Link="Shared/%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
