name: prerelease
on:
  release:
    branches: [main, devel, release/*]
    types:
      - prereleased
jobs:
  publish:
    name: Pre-release on ${{ matrix.os }}
    environment: Pre-release
    permissions:
      contents: read
      id-token: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET 10.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: |
          dotnet nuget locals all --clear
          dotnet build -p:Version=${GITHUB_REF#refs/tags/v} -c Release src/rclnet.sln
          dotnet build -p:Version=${GITHUB_REF#refs/tags/v} -c Release src/ros2cs.sln

      - name: Pack
        run: |
          dotnet pack -p:Version=${GITHUB_REF#refs/tags/v} -c Release --no-build -o bin/ src/Rosidl.Runtime
          dotnet pack -p:Version=${GITHUB_REF#refs/tags/v} -c Release --no-build -o bin/ src/Rcl.NET
          dotnet pack -p:Version=${GITHUB_REF#refs/tags/v} -c Release --no-build -o bin/ src/ros2cs
      
      - name: NuGet login
        id: nuget
        uses: NuGet/login@v1
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Publish NuGet Packages
        working-directory: bin
        run: |
          dotnet nuget push *.nupkg --api-key "${{ steps.nuget.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
